# docker-compose.yml
version: '3.8'

services:
  hello-world-web:
    build: .
    ports:
      - "3003:80"
    container_name: hello-world-website
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - web-network

networks:
  web-network:
    driver: bridge